/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"


void
calculadora_1(char *host)
{
	CLIENT *clnt;
	double  *result_1;
	double suma_1_arg1;
	double suma_1_arg2;
	double  *result_2;
	double resta_1_arg1;
	double resta_1_arg2;
	double  *result_3;
	double multiplicacion_1_arg1;
	double multiplicacion_1_arg2;
	double  *result_4;
	double division_1_arg1;
	double division_1_arg2;
	int  *result_5;
	int modulo_1_arg1;
	int modulo_1_arg2;
	double  *result_6;
	double potencia_1_arg1;
	int potencia_1_arg2;
	double  *result_7;
	int raiz_1_arg1;
	double raiz_1_arg2;
	double  *result_8;
	double log_nat_1_arg1;
	double  *result_9;
	double log10_1_arg1;
	double  *result_10;
	double seno_1_arg1;
	double  *result_11;
	double coseno_1_arg1;
	double  *result_12;
	double tangente_1_arg1;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA, BASICA, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = suma_1(suma_1_arg1, suma_1_arg2, clnt);
	if (result_1 == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = resta_1(resta_1_arg1, resta_1_arg2, clnt);
	if (result_2 == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = multiplicacion_1(multiplicacion_1_arg1, multiplicacion_1_arg2, clnt);
	if (result_3 == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = division_1(division_1_arg1, division_1_arg2, clnt);
	if (result_4 == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = modulo_1(modulo_1_arg1, modulo_1_arg2, clnt);
	if (result_5 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_6 = potencia_1(potencia_1_arg1, potencia_1_arg2, clnt);
	if (result_6 == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_7 = raiz_1(raiz_1_arg1, raiz_1_arg2, clnt);
	if (result_7 == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_8 = log_nat_1(log_nat_1_arg1, clnt);
	if (result_8 == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_9 = log10_1(log10_1_arg1, clnt);
	if (result_9 == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_10 = seno_1(seno_1_arg1, clnt);
	if (result_10 == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_11 = coseno_1(coseno_1_arg1, clnt);
	if (result_11 == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_12 = tangente_1(tangente_1_arg1, clnt);
	if (result_12 == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	calculadora_1 (host);
exit (0);
}
