/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static double *
_suma_1 (suma_1_argument *argp, struct svc_req *rqstp)
{
	return (suma_1_svc(argp->arg1, argp->arg2, rqstp));
}

static double *
_resta_1 (resta_1_argument *argp, struct svc_req *rqstp)
{
	return (resta_1_svc(argp->arg1, argp->arg2, rqstp));
}

static double *
_multiplicacion_1 (multiplicacion_1_argument *argp, struct svc_req *rqstp)
{
	return (multiplicacion_1_svc(argp->arg1, argp->arg2, rqstp));
}

static double *
_division_1 (division_1_argument *argp, struct svc_req *rqstp)
{
	return (division_1_svc(argp->arg1, argp->arg2, rqstp));
}

static int *
_modulo_1 (modulo_1_argument *argp, struct svc_req *rqstp)
{
	return (modulo_1_svc(argp->arg1, argp->arg2, rqstp));
}

static double *
_potencia_1 (potencia_1_argument *argp, struct svc_req *rqstp)
{
	return (potencia_1_svc(argp->arg1, argp->arg2, rqstp));
}

static double *
_raiz_1 (raiz_1_argument *argp, struct svc_req *rqstp)
{
	return (raiz_1_svc(argp->arg1, argp->arg2, rqstp));
}

static double *
_log_nat_1 (double  *argp, struct svc_req *rqstp)
{
	return (log_nat_1_svc(*argp, rqstp));
}

static double *
_log10_1 (double  *argp, struct svc_req *rqstp)
{
	return (log10_1_svc(*argp, rqstp));
}

static double *
_seno_1 (double  *argp, struct svc_req *rqstp)
{
	return (seno_1_svc(*argp, rqstp));
}

static double *
_coseno_1 (double  *argp, struct svc_req *rqstp)
{
	return (coseno_1_svc(*argp, rqstp));
}

static double *
_tangente_1 (double  *argp, struct svc_req *rqstp)
{
	return (tangente_1_svc(*argp, rqstp));
}

static void
calculadora_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		suma_1_argument suma_1_arg;
		resta_1_argument resta_1_arg;
		multiplicacion_1_argument multiplicacion_1_arg;
		division_1_argument division_1_arg;
		modulo_1_argument modulo_1_arg;
		potencia_1_argument potencia_1_arg;
		raiz_1_argument raiz_1_arg;
		double log_nat_1_arg;
		double log10_1_arg;
		double seno_1_arg;
		double coseno_1_arg;
		double tangente_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case SUMA:
		_xdr_argument = (xdrproc_t) xdr_suma_1_argument;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _suma_1;
		break;

	case RESTA:
		_xdr_argument = (xdrproc_t) xdr_resta_1_argument;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _resta_1;
		break;

	case MULTIPLICACION:
		_xdr_argument = (xdrproc_t) xdr_multiplicacion_1_argument;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _multiplicacion_1;
		break;

	case DIVISION:
		_xdr_argument = (xdrproc_t) xdr_division_1_argument;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _division_1;
		break;

	case MODULO:
		_xdr_argument = (xdrproc_t) xdr_modulo_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _modulo_1;
		break;

	case POTENCIA:
		_xdr_argument = (xdrproc_t) xdr_potencia_1_argument;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _potencia_1;
		break;

	case RAIZ:
		_xdr_argument = (xdrproc_t) xdr_raiz_1_argument;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _raiz_1;
		break;

	case LOG_NAT:
		_xdr_argument = (xdrproc_t) xdr_double;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _log_nat_1;
		break;

	case LOG10:
		_xdr_argument = (xdrproc_t) xdr_double;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _log10_1;
		break;

	case SENO:
		_xdr_argument = (xdrproc_t) xdr_double;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _seno_1;
		break;

	case COSENO:
		_xdr_argument = (xdrproc_t) xdr_double;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _coseno_1;
		break;

	case TANGENTE:
		_xdr_argument = (xdrproc_t) xdr_double;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _tangente_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (CALCULADORA, BASICA);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, CALCULADORA, BASICA, calculadora_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (CALCULADORA, BASICA, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, CALCULADORA, BASICA, calculadora_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (CALCULADORA, BASICA, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
