/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static double *
_suma_2 (suma_2_argument *argp, struct svc_req *rqstp)
{
	return (suma_2_svc(argp->arg1, argp->arg2, rqstp));
}

static double *
_resta_2 (resta_2_argument *argp, struct svc_req *rqstp)
{
	return (resta_2_svc(argp->arg1, argp->arg2, rqstp));
}

static double *
_multiplicacion_2 (multiplicacion_2_argument *argp, struct svc_req *rqstp)
{
	return (multiplicacion_2_svc(argp->arg1, argp->arg2, rqstp));
}

static double *
_division_2 (division_2_argument *argp, struct svc_req *rqstp)
{
	return (division_2_svc(argp->arg1, argp->arg2, rqstp));
}

static int *
_modulo_2 (modulo_2_argument *argp, struct svc_req *rqstp)
{
	return (modulo_2_svc(argp->arg1, argp->arg2, rqstp));
}

static double *
_potencia_2 (potencia_2_argument *argp, struct svc_req *rqstp)
{
	return (potencia_2_svc(argp->arg1, argp->arg2, rqstp));
}

static double *
_raiz_2 (raiz_2_argument *argp, struct svc_req *rqstp)
{
	return (raiz_2_svc(argp->arg1, argp->arg2, rqstp));
}

static double *
_log_nat_2 (double  *argp, struct svc_req *rqstp)
{
	return (log_nat_2_svc(*argp, rqstp));
}

static double *
_log10_2 (double  *argp, struct svc_req *rqstp)
{
	return (log10_2_svc(*argp, rqstp));
}

static double *
_seno_2 (double  *argp, struct svc_req *rqstp)
{
	return (seno_2_svc(*argp, rqstp));
}

static double *
_coseno_2 (double  *argp, struct svc_req *rqstp)
{
	return (coseno_2_svc(*argp, rqstp));
}

static double *
_tangente_2 (double  *argp, struct svc_req *rqstp)
{
	return (tangente_2_svc(*argp, rqstp));
}

static void
calculadora_2(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		suma_2_argument suma_2_arg;
		resta_2_argument resta_2_arg;
		multiplicacion_2_argument multiplicacion_2_arg;
		division_2_argument division_2_arg;
		modulo_2_argument modulo_2_arg;
		potencia_2_argument potencia_2_arg;
		raiz_2_argument raiz_2_arg;
		double log_nat_2_arg;
		double log10_2_arg;
		double seno_2_arg;
		double coseno_2_arg;
		double tangente_2_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case SUMA:
		_xdr_argument = (xdrproc_t) xdr_suma_2_argument;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _suma_2;
		break;

	case RESTA:
		_xdr_argument = (xdrproc_t) xdr_resta_2_argument;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _resta_2;
		break;

	case MULTIPLICACION:
		_xdr_argument = (xdrproc_t) xdr_multiplicacion_2_argument;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _multiplicacion_2;
		break;

	case DIVISION:
		_xdr_argument = (xdrproc_t) xdr_division_2_argument;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _division_2;
		break;

	case MODULO:
		_xdr_argument = (xdrproc_t) xdr_modulo_2_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _modulo_2;
		break;

	case POTENCIA:
		_xdr_argument = (xdrproc_t) xdr_potencia_2_argument;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _potencia_2;
		break;

	case RAIZ:
		_xdr_argument = (xdrproc_t) xdr_raiz_2_argument;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _raiz_2;
		break;

	case LOG_NAT:
		_xdr_argument = (xdrproc_t) xdr_double;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _log_nat_2;
		break;

	case LOG10:
		_xdr_argument = (xdrproc_t) xdr_double;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _log10_2;
		break;

	case SENO:
		_xdr_argument = (xdrproc_t) xdr_double;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _seno_2;
		break;

	case COSENO:
		_xdr_argument = (xdrproc_t) xdr_double;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _coseno_2;
		break;

	case TANGENTE:
		_xdr_argument = (xdrproc_t) xdr_double;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _tangente_2;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (CALCULADORA, BASICA);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, CALCULADORA, BASICA, calculadora_2, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (CALCULADORA, BASICA, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, CALCULADORA, BASICA, calculadora_2, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (CALCULADORA, BASICA, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
